name: Build binaries Linux, Macos

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build binary for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-latest,  macOS-11, macOS-latest]

    steps:
      - name: Provide gfortran (macOS)
        if: runner.os == 'macOS'
        run: |
          # https://github.com/actions/virtual-environments/issues/2524
          # https://github.com/cbg-ethz/dce/blob/master/.github/workflows/pkgdown.yaml
          sudo ln -s /usr/local/bin/gfortran-12 /usr/local/bin/gfortran
          sudo ln -s /usr/local/bin/gcc-12 /usr/local/bin/gcc
          sudo mkdir /usr/local/gfortran
          sudo ln -s /usr/local/Cellar/gcc@12/*/lib/gcc/12 /usr/local/gfortran/lib
          gfortran --version
          gcc --version
          which gcc
          which gfortran

      - name: Provide fftw  (macOS)
        if: runner.os == 'macOS'
        run: |
          # fftw3 
          brew install fftw
          fftw-wisdom -V
            
      - uses: actions/checkout@v3

      - name: Build binaries
        run: |
             cmake -S . -B build 
             cmake --build build
             ls ./bin

      - uses: actions/upload-artifact@v3
        with:
          path: ./bin/*
